; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico

[env:d1_mini]
platform = espressif8266
board = d1_mini
build_flags = -DWEMOSD1MINI=1 -DDEFAULTS_ON
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.7.0
	knolleary/PubSubClient@^2.8
	ropg/ezTime@^0.8.3
	majicdesigns/MD_MAXPanel@^1.2.3
	majicdesigns/MD_MAX72XX@^3.2.3
	adafruit/Adafruit BME280 Library@^2.1.2
	adafruit/Adafruit Unified Sensor@^1.1.4
	lorol/LittleFS_esp32
	bblanchon/ArduinoTrace @ ^1.2.0
	miguelbalboa/MFRC522 @ ^1.4.11
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp8266_exception_decoder

[env:ESP32_DOIT]
platform = espressif32
board_build.partitions = esp32Partitions.csv
build_flags = -DESP32DOIT -DDEFAULTS_ON
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.7.0
	knolleary/PubSubClient@^2.8
	madhephaestus/ESP32Servo@^0.9.0
	ropg/ezTime@^0.8.3
	majicdesigns/MD_MAXPanel@^1.2.3
	majicdesigns/MD_MAX72XX@^3.2.3
	adafruit/Adafruit BME280 Library@^2.1.2
	adafruit/Adafruit Unified Sensor@^1.1.4
	bblanchon/ArduinoTrace @ ^1.2.0
debug_tool = esp-prog
debug_init_break = tbreak setup

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
build_flags = -DARDUINO_ARCH_PICO -DDEFAULTS_ON
	-D DISTANCE_TRIG_PIN=14
	-D DISTANCE_ECHO_PIN=15
	-D L_MOTOR_B1=10
	-D L_MOTOR_B2=11
	-D L_MOTOR_B3=12
	-D L_MOTOR_B4=13
	-D R_MOTOR_B1=9
	-D R_MOTOR_B2=8
	-D R_MOTOR_B3=7
	-D R_MOTOR_B4=6
	-D SOUND_GPIO=16
	-D NEOPIN=28
board_build.core = earlephilhower
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.7.0
	knolleary/PubSubClient@^2.8
	madhephaestus/ESP32Servo@^0.9.0
	ropg/ezTime@^0.8.3
	majicdesigns/MD_MAXPanel@^1.2.3
	majicdesigns/MD_MAX72XX@^3.2.3
	adafruit/Adafruit BME280 Library@^2.1.2
	adafruit/Adafruit Unified Sensor@^1.1.4
	bblanchon/ArduinoTrace @ ^1.2.0
	miguelbalboa/MFRC522 @ ^1.4.11
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
monitor_speed = 115200
monitor_port = COM20
